#!/usr/bin/env python3
import argparse
import os

parser = argparse.ArgumentParser(description='output chrlist.txt and chrlen.txt for cisgenome')
parser.add_argument('-i', '--input', type=str, metavar='<path>', required=True,
	help='input genome.fa')
parser.add_argument('-o', '--output_directory', type=str, metavar='<path>', default='.', 
	required=False, help='output directory [default: .]')
arg = parser.parse_args()

os.system(f'mkdir {arg.output_directory} -p')
chrlist = open(f'{arg.output_directory}/chrlist.txt', 'w')
chrlen  = open(f'{arg.output_directory}/chrlen.txt', 'w')

length = 0
with open(arg.input) as fh:
	while True:
		line = fh.readline()
		if line == '': break
		line = line.rstrip()
		if line.startswith('>'):
			if length > 0: 
				chrlen.write(f'{length}\n')
				chrlist.write(f'{line[1:]}\n')
				length = 0
			else:
				chrlist.write(f'{line[1:]}\n')
		else:
			length += len(line)
	chrlen.write(f'{length}\n')
