#!/usr/bin/env python3
import argparse

parser = argparse.ArgumentParser(description='Make Snakefiles')
parser.add_argument('-a', '--aligner', type=str, metavar='<str>', required=False,
	help='input sequence aligner {bwa_mem, bowtie2, STAR} (default: bwa_mem)')
parser.add_argument('-p', '--peakcaller', type=str, metavar='<str>', required = False,
	help='input peak calling program {macs2, macs3} (default: macs3)' )
parser.add_argument('-nd', '--no_deduplication', action='store_true',
	help='if tagged, bam files will not be deduplicated')
arg = parser.parse_args()

