{% set name = "rocketchip" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/db/db/5a4db480cc246324617908efc1aee220e0aae769509fd788594b7c08b6f8/rocketchip-2.0.1.tar.gz
  sha256: bb2bd78f0e15c7c9be82d8a19832f0b042dfba0a5d6f6a3c5aaf9c6d72ef3153

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed
  
requirements:
  host:
    - python
    - pip
    - curl
  run:
    - python
    - pyyaml >=6.0.1
    - snakemake >=7.32.4
    - bowtie2 >=2.5.2  
    - bwa >=0.7.17     
    - deeptools >=3.5.4
    - fastqc >=0.12.1  
    - genrich >=0.6.1  
    - macs3 <=3.0.3
    - pepr >=1.1.24    
    - picard <=3.1.1
    - pip
    - sambamba >=1.0.0 
    - samtools >=1.18  
    - snakemake-minimal =7.32.4
    - sra-tools =3.0.9 
    - star >=2.7.11a   

test:
  imports:
    - yaml
  commands:
    - rocketchip --help

about:
  home: https://github.com/vhaghani26/rocketchip
  license: MIT
  summary: 'Rocketchip: chromatin immunoprecipitation data analysis'
  
extra:
  channels:
    - conda-forge